### ISSUE TITLE
test failing on unrecognized SSL message.

### ISSUE THREAD

**Issue by thunderkid** [cuali/SprayEasterEggs#6]
I'm getting errors when I run the test. I'm using sbt 0.13.8. Printout below. I get the same errors when I re-start. Are there any steps required that aren't listed in the README or am I missing something? Thanks.

10:12:14.510 INFO  [akka://EchoWebSocketTest/user/IO-UHTTP/group-0/0] akka.actor
.LocalActorRef - Message [spray.io.SslTlsSupportPatched$WriteChunkAck$] from Act
or[akka://EchoWebSocketTest/system/IO-TCP/selectors/$a/1#874820358] to Actor[akk
a://EchoWebSocketTest/user/IO-UHTTP/group-0/0#-2056242547] was not delivered. [2
] dead letters encountered. This logging can be turned off or adjusted with conf
iguration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shu
tdown'.
[info] - websocket echo
10:12:15.526 INFO  [] akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] WebSocketTest:
10:12:15.538 INFO  [akka://reactive-socket-WebSocketTest/user/IO-UHTTP/listener-
0] s.can.server.UpgradableHttpListener - Bound to /0.0.0.0:6696
10:12:15.539 INFO  [akka://reactive-socket-WebSocketTest/deadLetters] akka.actor
.DeadLetterActorRef - Message [akka.io.Tcp$Bound] from Actor[akka://reactive-soc
ket-WebSocketTest/user/IO-UHTTP/listener-0#-459995700] to Actor[akka://reactive-
socket-WebSocketTest/deadLetters] was not delivered. [1] dead letters encountere
d. This logging can be turned off or adjusted with configuration settings 'akka.
log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
10:12:18.573 ERROR [akka://reactive-socket-WebSocketTest/user/IO-UHTTP/listener-
0/0] s.can.server.HttpServerConnection - Aborting encrypted connection to /192.1
68.1.114:58882 due to [SSLException:Unrecognized SSL message, plaintext connecti
on?]
10:12:18.574 ERROR [akka://reactive-socket-WebSocketTest/user/IO-UHTTP/listener-
0/1] s.can.server.HttpServerConnection - Aborting encrypted connection to /192.1
68.1.114:58881 due to [SSLException:Unrecognized SSL message, plaintext connecti
on?]
[info] - websocket connection *** FAILED ***
[info]   None equaled None (WebSocketTest.scala:50)
10:12:21.577 INFO  [] akka.event.slf4j.Slf4jLogger - Slf4jLogger started
10:12:21.590 INFO  [ActorSystem(reactive-hide-HideServiceSpec)] akka.actor.Actor
SystemImpl - http://example.com/hide
[info] HideServiceSpec

**Comment by Alain-Bearez** [comment]
The latest commit should have fixed exactly this issue. Please confirm it is now passing the tests and close this issue.

Since the tests are run locally, I should have left the ```ssl-encryption``` setting as ```off```.

The tutorial is still lacking a section about turning on the SSL encryption in order to use HTTPS and WSS for this toy project.

**Comment by thunderkid** [comment]
Well, the test now passes. But when I try to run it with sbt re-start I get the following errors and an "oh snap" error in the browser:

> re-start
[info] Application sprayeastereggs3 not yet started
[info] Starting application sprayeastereggs3 in the background ...
sprayeastereggs3 Starting reactive.ReactiveSystem.main()
[success] Total time: 0 s, completed May 7, 2015 4:20:08 PM
> sprayeastereggs3 16:20:09.283 INFO  [] akka.event.slf4j.Slf4jLogger - Slf4jLog
ger started
sprayeastereggs3 16:20:09.664 INFO  [akka://reactive-system/deadLetters] akka.ac
tor.DeadLetterActorRef - Message [akka.io.Tcp$Bound] from Actor[akka://reactive-
system/system/IO-TCP/selectors/$a/0#1537912923] to Actor[akka://reactive-system/
deadLetters] was not delivered. [1] dead letters encountered. This logging can b
e turned off or adjusted with configuration settings 'akka.log-dead-letters' and
 'akka.log-dead-letters-during-shutdown'.
sprayeastereggs3 16:20:09.920 INFO  [akka://reactive-system/user/IO-HTTP/listene
r-0] spray.can.server.HttpListener - Bound to /0.0.0.0:9692
sprayeastereggs3 16:20:09.920 INFO  [akka://reactive-system/deadLetters] akka.ac
tor.DeadLetterActorRef - Message [akka.io.Tcp$Bound] from Actor[akka://reactive-
system/user/IO-HTTP/listener-0#919988183] to Actor[akka://reactive-system/deadLe
tters] was not delivered. [2] dead letters encountered. This logging can be turn
ed off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka
.log-dead-letters-during-shutdown'.
sprayeastereggs3 16:20:09.921 INFO  [akka://reactive-system/user/IO-UHTTP/listen
er-0] s.can.server.UpgradableHttpListener - Bound to /0.0.0.0:6696
sprayeastereggs3 16:20:09.921 INFO  [akka://reactive-system/deadLetters] akka.ac
tor.DeadLetterActorRef - Message [akka.io.Tcp$Bound] from Actor[akka://reactive-
system/user/IO-UHTTP/listener-0#1896980713] to Actor[akka://reactive-system/dead
Letters] was not delivered. [3] dead letters encountered. This logging can be tu
rned off or adjusted with configuration settings 'akka.log-dead-letters' and 'ak
ka.log-dead-letters-during-shutdown'.
sprayeastereggs3 16:20:11.410 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/
sprayeastereggs3 16:20:11.657 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/find/index.html
sprayeastereggs3 16:20:11.659 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/hide/index.html
sprayeastereggs3 16:20:11.726 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/find/find.js
sprayeastereggs3 16:20:11.726 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/css/panel.css
sprayeastereggs3 16:20:11.762 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/hide/hide.js
sprayeastereggs3 16:20:12.035 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/0] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.056 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/1] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.068 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/2] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.083 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/3] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.097 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/4] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.111 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/5] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.125 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/6] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.139 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/7] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.154 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/8] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:12.452 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/favicon.ico
sprayeastereggs3 16:20:31.134 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/
sprayeastereggs3 16:20:31.336 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/find/index.html
sprayeastereggs3 16:20:31.337 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/hide/index.html
sprayeastereggs3 16:20:31.407 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/hide/hide.js
sprayeastereggs3 16:20:31.407 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/css/panel.css
sprayeastereggs3 16:20:31.452 INFO  [ActorSystem(reactive-system)] akka.actor.Ac
torSystemImpl - http://localhost:9692/find/find.js
sprayeastereggs3 16:20:31.705 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/9] s.can.server.HttpServerConnection - Illegal request, responding with sta
tus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:31.719 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/10] s.can.server.HttpServerConnection - Illegal request, responding with st
atus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:31.733 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/11] s.can.server.HttpServerConnection - Illegal request, responding with st
atus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:31.745 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/12] s.can.server.HttpServerConnection - Illegal request, responding with st
atus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:31.761 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/13] s.can.server.HttpServerConnection - Illegal request, responding with st
atus '501 Not Implemented': Unsupported HTTP method
sprayeastereggs3 16:20:31.775 WARN  [akka://reactive-system/user/IO-UHTTP/listen
er-0/14] s.can.server.HttpServerConnection - Illegal request, responding with st
atus '501 Not Implemented': Unsupported HTTP method

**Comment by Alain-Bearez** [comment]
This was a little ```s``` that remained from my tests with SSL certificate.

The JavaScript code now adapts the WebSocket protocol to be either ```ws://``` when the page is opened with ```http://``` or ```wss://``` when the page is opened with ```https://``` (this depends on the configuration ```spray.can.server.ssl-encryption``` in ```the application.conf```)

**Comment by thunderkid** [comment]
Ok, that fixed it and it's now running. Thanks. Very nice project!
